version: "3.8"

name: evobot
services:
  evobot:
    container_name: evobot
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${PORT:-9100}:${INTERNAL_METRICS_PORT:-3000}"
