name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy sources to server
        run: rsync -avz ./ root@${{ secrets.SSH_HOST }}:/home/ci/apps/evobot_fresh
      - name: Build & run application
        run: >-
          ssh root@${{ secrets.SSH_HOST }}
          '
            uptime;
            cd /home/ci/apps;
            rm -rf evobot_prev;
            mv evobot evobot_prev;
            mv evobot_fresh evobot;
            cp envs/evobot.config.json evobot/config.json;
            cd evobot;
            docker compose build --no-cache;
            docker compose up -d;
          '
